/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.facebook.research.asynchronousratchetingtree.art.message.thrift;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import java.util.BitSet;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.facebook.thrift.*;
import com.facebook.thrift.async.*;
import com.facebook.thrift.meta_data.*;
import com.facebook.thrift.server.*;
import com.facebook.thrift.transport.*;
import com.facebook.thrift.protocol.*;

@SuppressWarnings({ "unused", "serial" })
public class AuthenticatedMessageStruct implements TBase, java.io.Serializable, Cloneable, Comparable<AuthenticatedMessageStruct> {
  private static final TStruct STRUCT_DESC = new TStruct("AuthenticatedMessageStruct");
  private static final TField MESSAGE_FIELD_DESC = new TField("message", TType.STRING, (short)1);
  private static final TField AUTHENTICATOR_FIELD_DESC = new TField("authenticator", TType.STRING, (short)2);

  public byte[] message;
  public byte[] authenticator;
  public static final int MESSAGE = 1;
  public static final int AUTHENTICATOR = 2;
  public static boolean DEFAULT_PRETTY_PRINT = true;

  // isset id assignments

  public static final Map<Integer, FieldMetaData> metaDataMap;
  static {
    Map<Integer, FieldMetaData> tmpMetaDataMap = new HashMap<Integer, FieldMetaData>();
    tmpMetaDataMap.put(MESSAGE, new FieldMetaData("message", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    tmpMetaDataMap.put(AUTHENTICATOR, new FieldMetaData("authenticator", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMetaDataMap);
  }

  static {
    FieldMetaData.addStructMetaDataMap(AuthenticatedMessageStruct.class, metaDataMap);
  }

  public AuthenticatedMessageStruct() {
  }

  public AuthenticatedMessageStruct(
    byte[] message,
    byte[] authenticator)
  {
    this();
    this.message = message;
    this.authenticator = authenticator;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AuthenticatedMessageStruct(AuthenticatedMessageStruct other) {
    if (other.isSetMessage()) {
      this.message = TBaseHelper.deepCopy(other.message);
    }
    if (other.isSetAuthenticator()) {
      this.authenticator = TBaseHelper.deepCopy(other.authenticator);
    }
  }

  public AuthenticatedMessageStruct deepCopy() {
    return new AuthenticatedMessageStruct(this);
  }

  @Deprecated
  public AuthenticatedMessageStruct clone() {
    return new AuthenticatedMessageStruct(this);
  }

  public byte[]  getMessage() {
    return this.message;
  }

  public AuthenticatedMessageStruct setMessage(byte[] message) {
    this.message = message;
    return this;
  }

  public void unsetMessage() {
    this.message = null;
  }

  // Returns true if field message is set (has been assigned a value) and false otherwise
  public boolean isSetMessage() {
    return this.message != null;
  }

  public void setMessageIsSet(boolean value) {
    if (!value) {
      this.message = null;
    }
  }

  public byte[]  getAuthenticator() {
    return this.authenticator;
  }

  public AuthenticatedMessageStruct setAuthenticator(byte[] authenticator) {
    this.authenticator = authenticator;
    return this;
  }

  public void unsetAuthenticator() {
    this.authenticator = null;
  }

  // Returns true if field authenticator is set (has been assigned a value) and false otherwise
  public boolean isSetAuthenticator() {
    return this.authenticator != null;
  }

  public void setAuthenticatorIsSet(boolean value) {
    if (!value) {
      this.authenticator = null;
    }
  }

  public void setFieldValue(int fieldID, Object value) {
    switch (fieldID) {
    case MESSAGE:
      if (value == null) {
        unsetMessage();
      } else {
        setMessage((byte[])value);
      }
      break;

    case AUTHENTICATOR:
      if (value == null) {
        unsetAuthenticator();
      } else {
        setAuthenticator((byte[])value);
      }
      break;

    default:
      throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
    }
  }

  public Object getFieldValue(int fieldID) {
    switch (fieldID) {
    case MESSAGE:
      return getMessage();

    case AUTHENTICATOR:
      return getAuthenticator();

    default:
      throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
    }
  }

  // Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
  public boolean isSet(int fieldID) {
    switch (fieldID) {
    case MESSAGE:
      return isSetMessage();
    case AUTHENTICATOR:
      return isSetAuthenticator();
    default:
      throw new IllegalArgumentException("Field " + fieldID + " doesn't exist!");
    }
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof AuthenticatedMessageStruct)
      return this.equals((AuthenticatedMessageStruct)that);
    return false;
  }

  public boolean equals(AuthenticatedMessageStruct that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_message = true && this.isSetMessage();
    boolean that_present_message = true && that.isSetMessage();
    if (this_present_message || that_present_message) {
      if (!(this_present_message && that_present_message))
        return false;
      if (!TBaseHelper.equalsSlow(this.message, that.message))
        return false;
    }

    boolean this_present_authenticator = true && this.isSetAuthenticator();
    boolean that_present_authenticator = true && that.isSetAuthenticator();
    if (this_present_authenticator || that_present_authenticator) {
      if (!(this_present_authenticator && that_present_authenticator))
        return false;
      if (!TBaseHelper.equalsSlow(this.authenticator, that.authenticator))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(AuthenticatedMessageStruct other) {
    if (other == null) {
      // See java.lang.Comparable docs
      throw new NullPointerException();
    }

    if (other == this) {
      return 0;
    }
    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMessage()).compareTo(other.isSetMessage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    lastComparison = TBaseHelper.compareTo(message, other.message);
    if (lastComparison != 0) {
      return lastComparison;
    }
    lastComparison = Boolean.valueOf(isSetAuthenticator()).compareTo(other.isSetAuthenticator());
    if (lastComparison != 0) {
      return lastComparison;
    }
    lastComparison = TBaseHelper.compareTo(authenticator, other.authenticator);
    if (lastComparison != 0) {
      return lastComparison;
    }
    return 0;
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin(metaDataMap);
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id)
      {
        case MESSAGE:
          if (field.type == TType.STRING) {
            this.message = iprot.readBinary();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case AUTHENTICATOR:
          if (field.type == TType.STRING) {
            this.authenticator = iprot.readBinary();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();


    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.message != null) {
      oprot.writeFieldBegin(MESSAGE_FIELD_DESC);
      oprot.writeBinary(this.message);
      oprot.writeFieldEnd();
    }
    if (this.authenticator != null) {
      oprot.writeFieldBegin(AUTHENTICATOR_FIELD_DESC);
      oprot.writeBinary(this.authenticator);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    return toString(DEFAULT_PRETTY_PRINT);
  }

  @Override
  public String toString(boolean prettyPrint) {
    return toString(1, prettyPrint);
  }

  @Override
  public String toString(int indent, boolean prettyPrint) {
    String indentStr = prettyPrint ? TBaseHelper.getIndentedString(indent) : "";
    String newLine = prettyPrint ? "\n" : "";
String space = prettyPrint ? " " : "";
    StringBuilder sb = new StringBuilder("AuthenticatedMessageStruct");
    sb.append(space);
    sb.append("(");
    sb.append(newLine);
    boolean first = true;

    sb.append(indentStr);
    sb.append("message");
    sb.append(space);
    sb.append(":").append(space);
    if (this. getMessage() == null) {
      sb.append("null");
    } else {
        int __message_size = Math.min(this. getMessage().length, 128);
        for (int i = 0; i < __message_size; i++) {
          if (i != 0) sb.append(" ");
          sb.append(Integer.toHexString(this. getMessage()[i]).length() > 1 ? Integer.toHexString(this. getMessage()[i]).substring(Integer.toHexString(this. getMessage()[i]).length() - 2).toUpperCase() : "0" + Integer.toHexString(this. getMessage()[i]).toUpperCase());
        }
        if (this. getMessage().length > 128) sb.append(" ...");
    }
    first = false;
    if (!first) sb.append("," + newLine);
    sb.append(indentStr);
    sb.append("authenticator");
    sb.append(space);
    sb.append(":").append(space);
    if (this. getAuthenticator() == null) {
      sb.append("null");
    } else {
        int __authenticator_size = Math.min(this. getAuthenticator().length, 128);
        for (int i = 0; i < __authenticator_size; i++) {
          if (i != 0) sb.append(" ");
          sb.append(Integer.toHexString(this. getAuthenticator()[i]).length() > 1 ? Integer.toHexString(this. getAuthenticator()[i]).substring(Integer.toHexString(this. getAuthenticator()[i]).length() - 2).toUpperCase() : "0" + Integer.toHexString(this. getAuthenticator()[i]).toUpperCase());
        }
        if (this. getAuthenticator().length > 128) sb.append(" ...");
    }
    first = false;
    sb.append(newLine + TBaseHelper.reduceIndent(indentStr));
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check that fields of type enum have valid values
  }

}

